services:
  hf-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: hf-client:local
    container_name: hf-client
    tty: true
    stdin_open: true
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - /mnt/user/sharedownload/download:/workspace
      - /mnt/user/appdata/hf-client/cache:/home/git/.cache/huggingface
      - /mnt/user/appdata/hf-client/ssh:/home/git/.ssh
    networks:
      - my-service-net

networks:
  my-service-net:
    external: true