services:
  source-git-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: source-git-client:local
    container_name: source-git-client
    tty: true
    stdin_open: true
    volumes:
      - /mnt/alonepool/alone/workspace-pro:/workspace
      - /mnt/user/appdata/source-git-client/ssh:/home/git/.ssh
    networks:
      - my-service-net

networks:
  my-service-net:
    external: true
