services:
  source-git-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: source-git-client:local
    container_name: source-git-client
    volumes:
      - /mnt/alonepool/alone/workspace-pro:/workspace
      - /mnt/user/appdata/source-git-home/ssh:/home/git/.ssh
