services:
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: z-my-seaweedfs
    ports:
      - "29333:9333"
      - "28080:8080"
      - "28888:8888" # Web 文件管理界面
      - "28333:8333" # 新增 S3 接口端口
    volumes:
      - /mnt/user/alone/seaweedfs_data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    # 开启S3 + Web登录账号密码，自行修改用户名/密码
    command: >
      server -dir=/data
      -s3
      -filer.password=admin:123456
    networks:
      - my-service-net

networks:
  my-service-net:
    external: true