# 暂时废弃，使用的是路径使用 minio/minio:RELEASE.2025-04-22T22-12-26Z 完整web 版本
services:
  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs
    ports:
      - "29333:9333"
      - "28080:8080"
      - "28888:8888"
      - "28333:8333"
    volumes:
      - /mnt/user/alone/seaweedfs_data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: server -dir=/data -filer -s3
    networks:
      - my-service-net

networks:
  my-service-net:
    external: true