services:
  source-git-client:
    build:
      context: .
      dockerfile: Dockerfile
    image: git-client:local
    container_name: git-client
    tty: true
    stdin_open: true
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - /mnt/alonepool/alone/workspace-pro:/workspace
      - /mnt/user/appdata/source-git-client/ssh:/home/git/.ssh
    networks:
      - my-service-net

networks:
  my-service-net:
    external: true
