x-claude-lark: &claude-lark
  build:
    context: .
    dockerfile: Dockerfile
  image: claude-lark:local
  hostname: claude-lark
  tty: true
  stdin_open: true
  restart: unless-stopped
  deploy:
    restart_policy:
      condition: on-failure
      max_attempts: 3
  networks:
    - my-service-net

services:
  claude-lark:
    <<: *claude-lark
    container_name: claude-lark
    volumes:
      - /data/volume/claude-lark:/data

  claude-lark-secretary:
    <<: *claude-lark
    container_name: claude-lark-secretary
    volumes:
      - /data/volume/claude-lark-secretary:/data
  claude-lark-secretary-self:
    <<: *claude-lark
    container_name: claude-lark-secretary-self
    volumes:
      - /data/volume/claude-lark-secretary-self:/data

networks:
  my-service-net:
    external: true
