services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: smba-fs-web
    restart: unless-stopped
    user: "1000:100"
    entrypoint: /bin/sh
    command: >-
      -c "
        db=/database/filebrowser.db;
        if [ ! -f \"\$db\" ]; then
          /filebrowser config init -d \"\$db\";
          /filebrowser users add unraidsmb 111111 --admin -d \"\$db\";
        fi;
        exec /filebrowser -d \"\$db\"
      "
    ports:
      - "58080:80"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /mnt/user/outerdir:/srv:rw
      - /mnt/user/appdata/filebrowser/database:/database:rw
      - /mnt/user/appdata/filebrowser/config:/config:rw

  samba:
    image: dperson/samba
    container_name: smba-fs
    restart: unless-stopped
    stdin_open: true
    tty: true
    user: "1000:100"
    tmpfs:
      - /tmp
    ports:
      - "55445:445/tcp"
    environment:
      TZ: Asia/Shanghai
      WORKGROUP: WORKGROUP
    volumes:
      - /mnt/user/appdata/smba:/etc/samba:rw
      - /mnt/user/outerdir:/mount:rw
    command: >-
      -u "unraidsmb;111111;1000;users;100"
      -s "outerdir;/mount;yes;no;no;unraidsmb;unraidsmb"
      -w "WORKGROUP"
