docker run
  -d
  --name='steam-headless'
  --net='host'
  --pids-limit 2048
  -e TZ="Asia/Shanghai"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="steam-headless"
  -e 'USER_PASSWORD'='123456'
  -e 'TZ'='Asia/Shanghai'
  -e 'USER_LOCALES'='en_US.UTF-8 UTF-8'
  -e 'NVIDIA_PATCH_VERSION'=''
  -e 'WEB_UI_MODE'='vnc'
  -e 'NVIDIA_VISIBLE_DEVICES'='all'
  -e 'NVIDIA_DRIVER_CAPABILITIES'='all'
  -e 'DISPLAY'=':55'
  -e 'MODE'='primary'
  -e 'PORT_NOVNC_WEB'='8083'
  -e 'ENABLE_VNC_AUDIO'='false'
  -e 'ENABLE_EVDEV_INPUTS'='true'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8083]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/Josh5/docker-steam-headless/master/images/steam-icon.png'
  -v '/mnt/alonepool/alone/steamdata':'/home/default':'rw'
  -v '/mnt/alonepool/alone/games':'/mnt/games':'rw'
  --hostname='SteamHeadless'
  --add-host='SteamHeadless:127.0.0.1'
  --restart='unless-stopped'
  --shm-size='2G'
  --ipc='host'
  -v '/tmp/.X11-unix/':'/tmp/.X11-unix/':'rw'
  -v '/tmp/pulse/':'/tmp/pulse/':'rw'
  --ulimit='nofile=1024:524288'
  --device='/dev/fuse'
  --device='/dev/uinput'
  --device-cgroup-rule='c 13:* rmw'
  --cap-add='NET_ADMIN'
  --cap-add='SYS_ADMIN'
  --cap-add='SYS_NICE'
  --security-opt='seccomp=unconfined' 'josh5/steam-headless:latest'
a779b695056ce4a2e7916a3a294b7274898ca9da403c4a629ce3f2e7dcc1a23f