services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    ports:
      - "30000:3000"
    volumes:
      - /data/volume/new-api:/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - my-service-net

networks:
  my-service-net:
    external: true
